modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "narutoxboruto"
version = "${version}"
displayName = "Naruto X Boruto"
authors = "Turgyn, Lusito"
description = '''
Step into the world of ninjas with the Naruto x Boruto mod for Minecraft!

Transform your gameplay with iconic jutsus, legendary weapons, and beloved characters from the Naruto universe.
Train in the ninja arts, unlock powerful abilities, and embark on epic quests to protect your village.
Whether you want to master the Sharingan or raid massive creatures, like Shukaku, this mod lets you live out your wildest ninja dreams.

From the Leaf Village to the depths of the Hidden Sand, build, battle and become a true shinobi in this Naruto adventure.
'''
#logoFile = ""

[[dependencies.narutoxboruto]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.narutoxboruto]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.narutoxboruto]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "narutoxboruto.mixins.json"
